# /docs/openapi.yaml
openapi: 3.1.0
info:
  version: 1.0.0
  title: Students app
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: This is a documentation of students app
    This is a documentation of students app
tags:
  - name: Students
    description: Operations about students.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /students:
    get:
      $ref: ../swagger/paths/students/get.yaml
    post:
      $ref: ../swagger/paths/students/post.yaml

  /students/{id}:
    get:
      $ref: ../swagger/paths/students/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/students/{id}/delete.yaml
    put:
      $ref: ../swagger/paths/students/{id}/put.yaml
    patch:
      $ref: ../swagger/paths/students/{id}/patch.yaml

  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/request-reset-email:
    post:
      $ref: ../swagger/paths/auth/request-reset-email.yaml
  /auth/reset-password:
    post:
      $ref: ../swagger/paths/auth/reset-password.yaml
  /auth/google:
    get:
      $ref: ../swagger/paths/auth/google.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
